### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by ans-qureshi** [tu-rbo/differentiable-particle-filters#2]
I ran the command "python3 simple.py" but got this error

```
Traceback (most recent call last):
  File "simple.py", line 50, in <module>
    train_dpf(plot=True)
  File "simple.py", line 11, in train_dpf
    train_data = load_data(data_path=data_path, filename=task + '_train')
  File "/home/anshqureshi/differentiable-particle-filters/utils/data_utils.py", line 47, in load_data
    data[key] = np.reshape(data[key], [-1, steps_per_episode] + list(data[key].shape[1:])).astype('float32')
MemoryError
```

**Comment by divyamrast** [comment]
The memory error is probably due to having less RAM. I think you would need a PC with at least 16GB of RAM in order to execute the code.

**Comment by ans-qureshi** [comment]
Ok @divyamrast
